export const projects = [
  {
    title: 'Page E-commerce',
    description: " Proyecto realizado de la pagina de retos de Frontend Mentor es sobre la vista de una pagina de producto ",
      image: '/images/ecommerce.jpg',
      tags: ['JavaScript', 'HTML', 'Sass'],
    source: 'https://luminous-sprinkles-6c13fe.netlify.app/',
    visit: 'https://github.com/Yovieiker/ecommerce',
    id: 0,
  },
  {
    title: 'expenses chart',
    description:"Proyecto realizado de la pagina de retos de Frontend Mentor es sobre mostrar grafica de gastos",
    image: '/images/exponses.jpg',
    tags: ['JavaScript', 'API', 'HTML','Sass'],
    source: 'https://funny-cupcake-c0cfb3.netlify.app/',
    visit: 'https://github.com/Yovieiker/Expenses-chart-component',
    id: 1,
  },
  {
    title: 'App Rick & Morty',
    description: "Proyecto sobre buscar personaje de la serie Rick & Morty, consumiendo informacion desde una API",
      image: '/images/Rick.png',
      tags: ['JavaScript', 'API', 'React'],
    source: 'https://comfy-haupia-236d6d.netlify.app/',
    visit: 'https://github.com/Yovieiker/rick-morty-course',
    id: 2,
  },
  {
    title: 'App Calculadora',
    description: "Proyecto de calculadora, elaborada en react de los Ejercicios de FreeCodeCamp",
    image: '/images/CalculadoraReact.png',
    tags: ['React'],
    source: 'https://resilient-dragon-ccd6eb.netlify.app/',
    visit: 'https://github.com/Yovieiker/App-Calculadora',
    id: 3,
  },
  {
    title: 'App Tareas',
    description: "Proyecto de agregar tarea, donde se puede marcar como lista, eliminar tarea",
      image: '/images/notas.png',
      tags: ['React'],
    source: 'https://magnificent-conkies-f0895d.netlify.app/',
    visit: 'https://github.com/Yovieiker/ListaTareas',
    id: 4,
  },
  {
    title: 'Calculadora',
    description: "Proyecto de la pagina FreeCodeCamp, sobre calculadora para poder obtener el certificado",
      image: '/images/calculadoraJs.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://codepen.io/yovi12/pen/qBxozKp',
    visit: 'https://codepen.io/yovi12/pen/qBxozKp',
    id: 5,
  },
  {
    title: 'Generador frases',
    description: "Proyecto de la pagina FreeCodeCamp, trata de mostrar frases e ir cambiando el color de fondo",
      image: '/images/frases.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://codepen.io/yovi12/pen/MWQQxoj',
    visit: 'https://codepen.io/yovi12/pen/MWQQxoj',
    id: 6,
  },
  {
    title: 'Drum Machine',
    description: "Proyecto de la pagina FreeCodeCamp, sobre caja de ritmo donde al presionar uno de los botones hace un sonido unico",
      image: '/images/Drum-Machine.png',
      tags: ['JavaScript'],
    source: 'https://codepen.io/yovi12/pen/VwQXNQJ',
    visit: 'https://codepen.io/yovi12/pen/VwQXNQJ',
    id: 7,
  },
  {
    title: 'Clock 25 + 5',
    description: "Proyecto de la pagina FreeCodeCamp, trata sobre un temporizador en el que darle start empieza su cuenta regresiva",
      image: '/images/clock.png',
      tags: ['JavaScript'],
    source: 'https://codepen.io/yovi12/pen/JjpLgwV',
    visit: 'https://codepen.io/yovi12/pen/JjpLgwV',
    id: 8,
  },
  
];

export const TimeLineData = [
  { year: 2021, text: 'Primero trabajo Desarrollador web jr'},
  { year: 2022, text: 'Segundo trabajo Desarrollador web jr'},
  { year: 2023, text: 'En Proceso'}
];
